# Change these first
owner: hootware # Your GitHub username
repo: status # Your GitHub repository name

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"

# Add your sites here
sites:
  - name: Hootware
    url: https://hootware.com
  - name: Don't Interrupt
    url: https://dontinterrupt.app
  - name: Don't Interrupt (www)
    url: https://www.dontinterrupt.app
    expectedStatusCodes:
      - 200
      - 301
      - 302

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.hootware.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://avatars0.githubusercontent.com/u/1462125?s=200&v=4
  name: Hootware Status
  introTitle: ""
  introMessage: This is the Hootware status page which uses **real-time** data using [Upptime](https://github.com/upptime/upptime)
  navbar:
  #  - title: Status
  #    href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO
